### ISSUE TITLE
Mash up of the GE Scraper with the UCSB Curriculum Search

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-utilities-GEscraper#12]
There is a project here that allows access to the UCSB Curriculum Search page.

   https://github.com/UCSB-CS56-Projects/cs56-utilities-ucsb-curriculum-htmlunit

That allows you to see what courses are being offered in a particular department in a particular quarter.

Do a mash up that allows you to see, for some GE area, which courses from that are are ACTUALLY BEING OFFERED in a particular quarter, e.g. S15.

Alternatively, do a mashup that allows you to see, for each GE on an area's list, a list of all quarters that course was offered (from among all the quarters currently available through the UCSB curriculum search page.)   This is helpful because the best 'predictor' of when a course will be offered (and indeed even whether it is EVER going to be offered again) is to see how often it was offered in the recent past, and which quarter(s) it was offered.

The next step would be to also indicate for each of those offerings what the enrollment is/was, and the total number of seats in the course, to see whether or not the course is/was/is likely to be full.

**Comment by SElegans** [comment]
F16 OK (500 pts)

**Comment by natashalee** [comment]
PR #37 fixes this with a hack of copying the UCSBCurriculumSearch code from the curriculum search project (https://github.com/UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum) 

It works but this is not what we want to do. Creating new issue:
We want to use the curriculum search as a library (API) for good design practices and maintainability. 

Possibly make an interface, that the curriculum scraper implements AND have a mock curriculum scraper with hardcoded values that allows you to run tests
