### ISSUE TITLE
Beautification

### ISSUE THREAD

**Issue by brentkirkland** [UCSB-CS56-Projects/cs56-utilities-GEscraper#14]
Updated comments and pointed out future refractoring

25 Points <- Paz approved

**Comment by PazZaitGivon** [comment]
I aprove yes but Im confused are you claiming you did this? (referencing commits would be helpful) or are you leaving this as an issue for the next generation?

**Comment by brentkirkland** [comment]
- [4ef402a](https://github.com/UCSB-CS56-Projects/cs56-utilities-GEscraper/commit/4ef402a6e0446bd3345eb746261b6a1e44e220fe)
- [bf97363](https://github.com/UCSB-CS56-Projects/cs56-utilities-GEscraper/commit/bf9736323315bf77bebfe3a5f4bd04547e9563a6) 
- [c40b7f7](https://github.com/UCSB-CS56-Projects/cs56-utilities-GEscraper/commit/c40b7f7961185e1cdb371f03fe65793c610c165e)

**Comment by brentkirkland** [comment]
We beautified for the extra 25 to complete 625

**Comment by PazZaitGivon** [comment]
You guys appear to have 700 points without this but sure

**Comment by brentkirkland** [comment]
oh. cool then! thanks Paz!

**Comment by PazZaitGivon** [comment]
https://github.com/UCSB-CS56-W15/cs56_w15_feedback_Pair_dlynch305_brentkirkland/blob/master/README.md
Here is your feedback repo with your feedback for labs 6 and 7 in the readme
