### ISSUE TITLE
Allow searching on multiple criteria

### ISSUE THREAD

**Issue by EasterAndJay** [ucsb-cs56-projects/cs56-utilities-GEscraper#19]
Let users find courses that fulfill say Area D and Ethnicity and Writing requirement.

Possibly implement a full boolean search
e.g. (Area D or Area E or Area G) and (Writ or Ethnicity)

Approved 350 points

**Comment by EasterAndJay** [comment]
Very similar to #6 consider merging into one issue. Only difference with this issue is the idea of a full boolean search.

**Comment by SElegans** [comment]
F16 OK (300 pts)

**Comment by scottpchow23** [comment]
Closing due to similarity to #6.
