### ISSUE TITLE
Program does not appear to be working

### ISSUE THREAD

**Issue by mastergberry** [UCSB-CS56-Projects/cs56-utilities-GEscraper#3]
It appears that this application is broken.  A year later after successfully compiling and running the program it seems to have broken.  When entering a course area to get GE's for it freezes and does not display the output it should.  I suspect the HTML contents of the page http://my.sa.ucsb.edu/catalog/current/UndergraduateEducation/AreaE.aspx have most likely changed and the code scraper needs to be re-worked to account for the new HTML.

~Estimated 200 points

**Comment by PazZaitGivon** [comment]
Program  no longer appears to freeze and does appear to display output now.
