### ISSUE TITLE
Engineering menu doesn't lead to list GEs

### ISSUE THREAD

**Issue by youxinjie** [ucsb-cs56-projects/cs56-utilities-GEscraper#33]
This repo is for GE courses, the engineering part is supposed to list the GE courses that acceptable to engineers. Therefore, the main menu for engineering should be remove. And the code of getting courses description can be move to the other repo: [https://github.com/UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum](url).

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by scottpchow23** [comment]
I'm closing this issue due to a lack of clarity on what is being proposed here.
