### ISSUE TITLE
Allow reuse

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-utilities-GEscraper#4]
Currently the program seems to close after one run through; it may be nicer to have it  run till asked to stop so people can look at multiple outputs without having to rerun

Estimated ~50 points

**Comment by dlynch305** [comment]
Added reuse.
Commit: 9e047f8a3dbb086ae2f863cc72bb43cd7db41ce0

**Comment by PazZaitGivon** [comment]
looks good!
