### ISSUE TITLE
Better user documentation

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-utilities-GEscraper#5]
Make the output easier for the users to understand. Some suggestions: parse department codes into department names, get full course name, label expected sections etc

estimated ~100 points

**Comment by dlynch305** [comment]
Added full course name: 16a36a48cee868aae1ab5bae6c00113ac4a40dc8

**Comment by dlynch305** [comment]
Done throughout all commits.

**Comment by dlynch305** [comment]
Done throughout all commits.

**Comment by dlynch305** [comment]
Done throughout all commits and check README.

**Comment by PazZaitGivon** [comment]
much better
