### ISSUE TITLE
Basic GUI

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-utilities-GEscraper#7]
Encapsulate into a GUI that is easier to work with.

Estimated ~200 points

**Comment by dlynch305** [comment]
Didn't make a GUI, but greatly the readability/usability of the application as a console program.

**Comment by PazZaitGivon** [comment]
referencing https://github.com/UCSB-CS56-Projects/cs56-utilities-GEscraper/issues/8
however this issue is still open

**Comment by EasterAndJay** [comment]
Instead of relying on user input, Make drop down boxes that restrict the input to be valid.

i.e) B-H, writ, ethn, etc all in a drop box.
Departments in their own dropdown box (make sure you allow the option to not select a department)

Approved for 500 points.

**Comment by Simon-Huynh** [comment]
Can also update the GUI to be more interactive. Like filtering the results, making the GUI a single unified window, and other bells and whistles.

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by Simon-Huynh** [comment]
- Added a GUI prompt in the form of a dropdown menu when scraper asks for Subject Area. 
- Added a GUI prompt in the form of a textinput box when scraper asks for department abbreviation. User can also input N (No). 
- Also made it so the output given to the user is presented in a pop-up (and scroll-able) window. Information is a lot easier to read than within a terminal.

**Comment by EasterAndJay** [comment]
Leaving open for above suggestions by @Simon-Huynh

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by natashalee** [comment]
closing, 200 points, pull request https://github.com/UCSB-CS56-Projects/cs56-utilities-GEscraper/pull/36
