### ISSUE TITLE
Better Formatting - Usability

### ISSUE THREAD

**Issue by brentkirkland** [UCSB-CS56-Projects/cs56-utilities-GEscraper#8]
The current format is hard to read. Update the formatting at the command line. Also add the course name. The formatting would include columns.

Estimated ~ 100 Points

**Comment by dlynch305** [comment]
Course Name: 16a36a48cee868aae1ab5bae6c00113ac4a40dc8

**Comment by PazZaitGivon** [comment]
much better now
